NFS_CORE_PARAM {
    Enable_NLM = false;
    Enable_RQUOTA = false;
    Protocols = 3, 4;
}

MDCACHE {
    Dir_Chunk = 0;
}

NFSv4 {
    Delegations = none;
    RecoveryBackend = rados_cluster;
    Minor_Versions = 1, 2;
}

EXPORT {
    Export_ID = 100;
    Protocols = 3, 4;
    Access_Type = RW;
    Path = /srv/nfs/share;
    Squash = No_Root_Squash;
    FSAL {
        Name = VFS;
    }
}

LOG {
    Default_Log_Level = EVENT;
}
