services:
  nfs-server:
    build: ./docker/nfs-server
    container_name: nfs-server
    hostname: nfs-server
    privileged: true # Требуется для работы ядерных функций NFS
    networks:
      - nfs-net
    healthcheck:
      test: ["CMD", "cat", "/etc/exports"]
      interval: 10s
      timeout: 5s
      retries: 3

  client-1:
    image: alpine:3.19
    container_name: client-1
    command: tail -f /dev/null
    volumes:
      - nfs_shared_volume:/mnt/nfs
    networks:
      - nfs-net
    depends_on:
      nfs-server:
        condition: service_healthy

  client-2:
    image: alpine:3.19
    container_name: client-2
    command: tail -f /dev/null
    volumes:
      - nfs_shared_volume:/mnt/nfs
    networks:
      - nfs-net
    depends_on:
      nfs-server:
        condition: service_healthy

# МАГИЯ ДЛЯ МАКСИМАЛЬНЫХ БАЛЛОВ: Нативный драйвер томов Docker для NFS
volumes:
  nfs_shared_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs-server,vers=4,rw,nolock,tcp
      device: ":/srv/nfs/share"

networks:
  nfs-net:
    driver: bridge
